input: 
  files:
    - './access.log'

outputFilter:
  - module: '@sematext/logagent-filter-output-sql'
    config:
      source: !!js/regexp /access.log|httpd/
      interval: 1
      queries:
        - SELECT 'apache_stats' as _type, AVG(size) as size_avg, count(method) as method_count, method from ? GROUP BY method
        - SELECT * FROM ? where status_code>399
output:
  elasticsearch:
    url: http://localhost:9200
    index: mylogs
